FROM ubuntu:20.04

RUN apt update && apt install -y curl git wget sudo

# Install Docker
RUN curl -fsSL https://get.docker.com -o get-docker.sh
RUN sh get-docker.sh

# Install Pterodactyl
RUN mkdir -p /app
WORKDIR /app
COPY install.sh .
RUN chmod +x install.sh

CMD ["./install.sh"]
